// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyZHWqDzSIVun_F2XzzNJE9dfEZJqqO0',
    appId: '1:79271194536:web:6162c0099401ac6c7fb79d',
    messagingSenderId: '79271194536',
    projectId: 'point-manager-dff26',
    authDomain: 'point-manager-dff26.firebaseapp.com',
    storageBucket: 'point-manager-dff26.firebasestorage.app',
    measurementId: 'G-G6ZVJPY7T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdviTNaAbislKPKfmZaNtZfk83hBV0G2U',
    appId: '1:79271194536:android:438862ae462bd4017fb79d',
    messagingSenderId: '79271194536',
    projectId: 'point-manager-dff26',
    storageBucket: 'point-manager-dff26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrVFB8DNixxoLvrvzy0dnNma4G0NEleo',
    appId: '1:79271194536:ios:394f808e76a4e8e17fb79d',
    messagingSenderId: '79271194536',
    projectId: 'point-manager-dff26',
    storageBucket: 'point-manager-dff26.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrVFB8DNixxoLvrvzy0dnNma4G0NEleo',
    appId: '1:79271194536:ios:394f808e76a4e8e17fb79d',
    messagingSenderId: '79271194536',
    projectId: 'point-manager-dff26',
    storageBucket: 'point-manager-dff26.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRyZHWqDzSIVun_F2XzzNJE9dfEZJqqO0',
    appId: '1:79271194536:web:6bfa6b6c4b9f31577fb79d',
    messagingSenderId: '79271194536',
    projectId: 'point-manager-dff26',
    authDomain: 'point-manager-dff26.firebaseapp.com',
    storageBucket: 'point-manager-dff26.firebasestorage.app',
    measurementId: 'G-MJQYQ6J09Q',
  );

}